#!/usr/bin/env zsh

kill-port () {
  lsof -ti ":${1:-4000}" | xargs kill -9
}

killport () {
  lsof -ti ":${1:-4000}" | xargs kill -9
}

flushdns () {
  sudo killall -HUP mDNSResponder
}

clearmodules () {
  rm -Rf ./node_modules ./**/node_modules/ ./**/build/ ./**/dist/
}

ungit () {
	rm -Rf ./.git ./**/.git
}

uuid () {
 uuidgen | tr 'A-Z' 'a-z' | tr -d '\n'
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
}

function make () {
  dir=$(pwd)
  while [[ "$dir" != "" && ! -e "$dir/Makefile" ]]; do
    dir=${dir%/*}
  done
  /usr/bin/make -C "$dir" $1
}

function docker-clear {
  docker system prune -a --volumes
}
